#!/usr/bin/env python3
"""Automate Google Cloud setup using declarative orchestration config.

Overview
--------
This script executes Google Cloud setup tasks from YAML configuration rather
than hardcoded Python logic. The architecture separates environment/runtime
settings from actionable cloud resources:

- Runtime config file (default: ``gcp_config.yaml``)
- Components config file (default: ``gcp_components.yaml``)

Execution Model
---------------
1. Load defaults, runtime config, and CLI overrides.
2. Validate required project configuration.
3. Configure local gcloud profile and authentication.
4. Execute component actions in declared order.

Why This Script Exists
----------------------
- Keep setup portable across projects and accounts.
- Support repeatable/idempotent infrastructure bootstrapping.
- Let teams extend setup by editing YAML instead of Python code.

Quick Usage
-----------
- Preview only: ``python setup_gcp.py --dry-run``
- Execute setup: ``python setup_gcp.py``
- Custom files:
    ``python setup_gcp.py --config my_runtime.yaml``
    ``--components-config my_components.yaml``
 
Author: Cris Magalang (crismag)
GitHub: https://github.com/crismag/GoogleCloudPlatform_Utilities
Last Updated: 2026-03-23

Author: Cris Magalang (crismag)
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional
from datetime import datetime, timezone

import yaml

# ---------------------------------------------------------------------------
# Console and logging constants
# ---------------------------------------------------------------------------
LOG_COLORS = {
    "success": "\033[92m",
    "error": "\033[91m",
    "warning": "\033[93m",
    "info": "\033[94m",
}
LOG_RESET = "\033[0m"

# ---------------------------------------------------------------------------
# Global runtime defaults
# ---------------------------------------------------------------------------
#
# These defaults keep the script runnable even when some config values are
# omitted. Runtime YAML and CLI options always take precedence.
DEFAULT_RUNTIME_CONFIG: Dict[str, Any] = {
    "project": {
        "id": "",
        "name": "",
        "number": "",
    },
    "gcloud": {
        "configuration_name": "gcp-automation",
        "account": "",
        "run_region": "",
        "compute_region": "",
        "compute_zone": "",
    },
    "auth": {
        "login_if_needed": True,
        "create_application_default_credentials": False,
        "set_quota_project_for_adc": True,
    },
    "defaults": {
        "service_account": {
            "name": "automation-service-account",
            "display_name": "Automation Service Account",
            "description": "Service account generated by setup automation",
        },
        "credentials": {
            "key_file": "service-account-key.json",
            "key_path": "./credentials",
            "overwrite_local_key": False,
            "allow_new_key_creation_if_keys_exist": False,
            "delete_existing_user_managed_keys_before_create": False,
            "write_env_file": True,
            "env_file": ".env.gcp",
            "activate_service_account_for_gcloud": False,
            "persist_google_application_credentials": False,
            "persist_google_cloud_project": False,
        },
    },
    "components_config": {
        "path": "gcp_components.yaml",
    },
    "execution": {
        "dry_run": False,
        "debug_level": 0,
    },
}


def deep_merge_dictionaries(
    base_dictionary: Dict[str, Any],
    override_dictionary: Dict[str, Any],
) -> Dict[str, Any]:
    """Recursively merge dictionaries and return a new dictionary."""
    merged_dictionary = dict(base_dictionary)

    for key, override_value in override_dictionary.items():
        base_value = merged_dictionary.get(key)
        if isinstance(base_value, dict) and isinstance(override_value, dict):
            merged_dictionary[key] = deep_merge_dictionaries(base_value, override_value)
        else:
            merged_dictionary[key] = override_value

    return merged_dictionary


class GCloudSetupAutomation:
    """Execute Google Cloud setup using declarative component actions.

    Class Responsibilities
    ----------------------
    - Load and validate runtime/component configuration.
    - Configure gcloud CLI session context for target project.
    - Dispatch each component action to a dedicated handler.
    - Keep execution idempotent (safe to re-run).

    Handler Pattern
    ---------------
    Component items declare an ``action`` value. Each action maps to one
    handler function in ``self.action_handlers``. To add a new component type:

    1. Implement a new ``_execute_*`` handler method.
    2. Register it in ``self.action_handlers``.
    3. Use it from ``gcp_components.yaml``.
    """

    def __init__(
        self,
        runtime_config_path: str,
        cli_override_dictionary: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Initialize automation with merged runtime config and loaded components.

        Args:
            runtime_config_path: Path to runtime YAML configuration.
            cli_override_dictionary: Optional config override from CLI arguments.
        """
        self.runtime_config_path = runtime_config_path
        self.runtime_config_directory = Path(runtime_config_path).resolve().parent
        self.cli_override_dictionary = cli_override_dictionary or {}

        self.runtime_config = self._load_runtime_configuration()
        self._validate_runtime_configuration()

        self.project_config = self.runtime_config["project"]
        self.gcloud_config = self.runtime_config["gcloud"]
        self.auth_config = self.runtime_config["auth"]
        self.defaults_config = self.runtime_config["defaults"]
        self.execution_config = self.runtime_config["execution"]
        self.gcloud_executable = self._resolve_gcloud_executable()

        # Debug level controls extra runtime output and recorded details:
        # 0 = normal (default), 1 = print commands executed
        # 2 = include stdout/stderr, 3 = full debug
        self.debug_level: int = int(self.execution_config.get("debug_level", 0))

        self.project_id = self.project_config["id"]
        self.project_name = self.project_config.get("name", "")
        self.project_number = self.project_config.get("number", "")

        self.components = self._load_components_configuration()
        self.action_handlers: Dict[str, Callable[[Dict[str, Any]], bool]] = {
            "enable_api": self._execute_enable_api,
            "ensure_service_account": self._execute_ensure_service_account,
            "ensure_service_account_key": self._execute_ensure_service_account_key,
            "ensure_project_iam_binding": self._execute_ensure_project_iam_binding,
            "configure_local_credentials": self._execute_configure_local_credentials,
        }

        # Structured run-log state
        self.run_log_entries: List[Dict[str, Any]] = []
        self.created_files: List[str] = []
        self.run_start_time: str = datetime.now(timezone.utc).isoformat()
        # Files are placed relative to runtime config directory
        self.run_log_path = self._resolve_path("setup_run_log.json")
        self.run_manifest_path = self._resolve_path("setup_manifest.json")
        self._last_action_artifacts: Optional[Dict[str, Any]] = None

    def _resolve_gcloud_executable(self) -> str:
        """Resolve the best gcloud executable for the current OS."""
        if os.name == "nt":
            return shutil.which("gcloud.cmd") or shutil.which("gcloud") or "gcloud"
        return shutil.which("gcloud") or "gcloud"

    def _load_runtime_configuration(self) -> Dict[str, Any]:
        """Load runtime config and merge it with defaults and CLI overrides."""
        # Runtime config controls execution behavior and environment details.
        runtime_config_data: Dict[str, Any] = {}
        runtime_config_file = Path(self.runtime_config_path)

        if runtime_config_file.exists():
            try:
                with open(runtime_config_file, "r", encoding="utf-8") as file_handle:
                    loaded_data = yaml.safe_load(file_handle)
                    runtime_config_data = (
                        loaded_data if isinstance(loaded_data, dict) else {}
                    )
                self._log("✓ Loaded runtime configuration", "success")
            except yaml.YAMLError as yaml_error:
                self._log(f"✗ Invalid YAML in runtime config: {yaml_error}", "error")
                sys.exit(1)
            except OSError as os_error:
                self._log(f"✗ Failed reading runtime config: {os_error}", "error")
                sys.exit(1)
        else:
            self._log(
                "⚠ Runtime config file not found; using defaults and CLI overrides",
                "warning",
            )

        merged_config = deep_merge_dictionaries(
            DEFAULT_RUNTIME_CONFIG,
            runtime_config_data,
        )
        merged_config = deep_merge_dictionaries(
            merged_config,
            self.cli_override_dictionary,
        )
        return merged_config

    def _load_components_configuration(self) -> List[Dict[str, Any]]:
        """Load orchestration components list from dedicated components config."""
        # Component config controls *what* cloud resources/actions to perform.
        components_path_setting = self.runtime_config.get("components_config", {}).get(
            "path",
            "gcp_components.yaml",
        )
        components_file_path = self._resolve_path(components_path_setting)

        if not components_file_path.exists():
            self._log(
                f"✗ Components config not found: {components_file_path}",
                "error",
            )
            sys.exit(1)

        try:
            with open(components_file_path, "r", encoding="utf-8") as file_handle:
                loaded_data = yaml.safe_load(file_handle)
        except yaml.YAMLError as yaml_error:
            self._log(f"✗ Invalid YAML in components config: {yaml_error}", "error")
            sys.exit(1)
        except OSError as os_error:
            self._log(f"✗ Failed reading components config: {os_error}", "error")
            sys.exit(1)

        components_data = loaded_data if isinstance(loaded_data, dict) else {}
        component_items = components_data.get("components", [])

        if not isinstance(component_items, list):
            self._log("✗ components must be a list in components config", "error")
            sys.exit(1)

        self._log(f"✓ Loaded {len(component_items)} component item(s)", "success")
        return component_items

    def _validate_runtime_configuration(self) -> None:
        """Validate required runtime configuration before executing steps."""
        project_id = self.runtime_config.get("project", {}).get("id", "").strip()
        if not project_id:
            self._log(
                "✗ Missing project.id. Set it in runtime config or with --project-id.",
                "error",
            )
            sys.exit(1)

    def _resolve_path(self, raw_path: str) -> Path:
        """Resolve relative paths against runtime config directory."""
        candidate_path = Path(raw_path)
        if candidate_path.is_absolute():
            return candidate_path
        return (self.runtime_config_directory / candidate_path).resolve()

    def _log(self, message: str, level: str = "info") -> None:
        """Write a colorized log message."""
        color_code = LOG_COLORS.get(level, "")
        print(f"{color_code}{message}{LOG_RESET}")

    def _run_command(
        self,
        command_arguments: List[str],
        check_return_code: bool = True,
        capture_output: bool = True,
    ) -> subprocess.CompletedProcess:
        """Run a command and return subprocess result.

        In dry-run mode, this prints the command and returns a successful
        completed result without executing.
        """
        # Centralized command runner keeps subprocess behavior consistent,
        # including dry-run behavior and uniform error handling.
        normalized_command_arguments = list(command_arguments)
        if normalized_command_arguments and normalized_command_arguments[0] == "gcloud":
            normalized_command_arguments[0] = self.gcloud_executable

        command_text = " ".join(normalized_command_arguments)
        if self.execution_config.get("dry_run", False):
            self._log(f"[dry-run] {command_text}", "info")
            # Don't duplicate debug prints when dry-run (dry-run already shows command)
            return subprocess.CompletedProcess(
                normalized_command_arguments,
                0,
                stdout="",
                stderr="",
            )

        # When debug level >=1 show the command being executed (only on real runs)
        if self.debug_level >= 1:
            self._log(f"[exec] {command_text}", "info")

        result = subprocess.run(
            normalized_command_arguments,
            capture_output=capture_output,
            text=True,
        )

        # Always record failed command exit code and stderr for structured logging
        if result.returncode != 0:
            try:
                self._last_action_artifacts = self._last_action_artifacts or {}
                self._last_action_artifacts["last_command"] = {
                    "cmd": command_text,
                    "returncode": result.returncode,
                    "stderr": (result.stderr.strip() if result.stderr else ""),
                }
            except Exception:
                # Best-effort only; don't let logging instrumentation break execution
                pass

        # If debug level >=2 include successful command stdout/stderr into last_command
        if self.debug_level >= 2 and result.returncode == 0:
            try:
                self._last_action_artifacts = self._last_action_artifacts or {}
                self._last_action_artifacts["last_command"] = {
                    "cmd": command_text,
                    "returncode": result.returncode,
                    "stdout": (result.stdout.strip() if result.stdout else ""),
                    "stderr": (result.stderr.strip() if result.stderr else ""),
                }
            except Exception:
                pass

        if check_return_code and result.returncode != 0:
            self._log(f"✗ Command failed: {command_text}", "error")
            if capture_output and result.stderr:
                self._log(f"  Error: {result.stderr.strip()}", "error")
            raise subprocess.CalledProcessError(
                result.returncode,
                normalized_command_arguments,
                output=result.stdout,
                stderr=result.stderr,
            )

        return result

    def _resolve_text_template(self, text_value: str, context: Dict[str, str]) -> str:
        """Resolve template placeholders in a string using provided context."""
        resolved_text = text_value
        for placeholder_name, placeholder_value in context.items():
            resolved_text = resolved_text.replace(
                "{" + placeholder_name + "}",
                str(placeholder_value),
            )
        return resolved_text

    def _resolve_argument_templates(
        self,
        component_arguments: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Resolve known placeholders inside string argument values."""
        # Placeholders make component YAML reusable across projects/accounts.
        service_account_name = component_arguments.get("service_account_name", "")
        if not service_account_name:
            service_account_name = self.defaults_config.get("service_account", {}).get(
                "name",
                "",
            )

        context_dictionary = {
            "project_id": self.project_id,
            "project_name": self.project_name,
            "project_number": self.project_number,
            "service_account_name": service_account_name,
            "service_account_email": (
                f"{service_account_name}@{self.project_id}.iam.gserviceaccount.com"
                if service_account_name
                else ""
            ),
        }

        resolved_arguments: Dict[str, Any] = {}
        for argument_name, argument_value in component_arguments.items():
            if isinstance(argument_value, str):
                resolved_arguments[argument_name] = self._resolve_text_template(
                    argument_value,
                    context_dictionary,
                )
            else:
                resolved_arguments[argument_name] = argument_value
        return resolved_arguments

    def _append_run_log_entry(
        self,
        component_id: str,
        action: str,
        args: Dict[str, Any],
        result: bool,
        message: Optional[str] = None,
        artifacts: Optional[List[str]] = None,
    ) -> None:
        """Append one entry to the in-memory run log."""
        entry: Dict[str, Any] = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "component_id": component_id,
            "action": action,
            "args": args,
            "result": "success" if result else "failure",
        }
        if message:
            entry["message"] = message
        if artifacts:
            entry["artifacts"] = artifacts
            for p in artifacts:
                if p not in self.created_files:
                    self.created_files.append(p)

        # If the last action recorded a failed command, include its details
        try:
            if isinstance(self._last_action_artifacts, dict):
                last_cmd = self._last_action_artifacts.get("last_command")
                if last_cmd:
                    entry["last_command"] = last_cmd
        except Exception:
            pass

        self.run_log_entries.append(entry)

    def _write_run_artifacts(self) -> None:
        """Write run log and manifest JSON files to disk."""
        run_end_time = datetime.now(timezone.utc).isoformat()
        manifest: Dict[str, Any] = {
            "project_id": self.project_id,
            "run_start": self.run_start_time,
            "run_end": run_end_time,
            "created_files": self.created_files,
        }

        try:
            # Write run log (list of entries)
            self.run_log_path.write_text(
                json.dumps(self.run_log_entries, indent=2), encoding="utf-8"
            )
            # Write manifest metadata
            self.run_manifest_path.write_text(
                json.dumps(manifest, indent=2), encoding="utf-8"
            )
            self._log(f"✓ Wrote run log: {self.run_log_path}", "success")
            self._log(f"✓ Wrote run manifest: {self.run_manifest_path}", "success")
        except OSError as write_error:
            self._log(f"⚠ Failed writing run artifacts: {write_error}", "warning")

    def _collect_enabled_api_services(self) -> List[str]:
        """Collect enabled API services for the active project."""
        result = self._run_command(
            [
                "gcloud",
                "services",
                "list",
                "--enabled",
                "--format=value(config.name)",
            ],
            check_return_code=False,
        )
        if result.returncode != 0 or not result.stdout:
            return []
        return [line.strip() for line in result.stdout.splitlines() if line.strip()]

    def _collect_user_managed_service_account_keys(
        self,
        service_account_email: str,
    ) -> List[Dict[str, Any]]:
        """Collect user-managed keys for a service account email."""
        result = self._run_command(
            [
                "gcloud",
                "iam",
                "service-accounts",
                "keys",
                "list",
                f"--iam-account={service_account_email}",
                "--managed-by=user",
                "--format=json",
            ],
            check_return_code=False,
        )

        if result.returncode != 0 or not result.stdout:
            return []

        try:
            parsed_data = json.loads(result.stdout)
            return parsed_data if isinstance(parsed_data, list) else []
        except json.JSONDecodeError:
            return []

    def _delete_user_managed_service_account_key(
        self,
        service_account_email: str,
        key_name: str,
    ) -> None:
        """Delete one user-managed key from a service account."""
        self._run_command(
            [
                "gcloud",
                "iam",
                "service-accounts",
                "keys",
                "delete",
                key_name,
                f"--iam-account={service_account_email}",
                "--quiet",
            ]
        )

    def _collect_project_iam_policy(self) -> Dict[str, Any]:
        """Collect project IAM policy in JSON form."""
        result = self._run_command(
            [
                "gcloud",
                "projects",
                "get-iam-policy",
                self.project_id,
                "--format=json",
            ],
            check_return_code=False,
        )

        if result.returncode != 0 or not result.stdout:
            return {}

        try:
            parsed_data = json.loads(result.stdout)
            return parsed_data if isinstance(parsed_data, dict) else {}
        except json.JSONDecodeError:
            return {}

    def _member_has_role_binding(
        self,
        iam_policy_dictionary: Dict[str, Any],
        iam_member: str,
        iam_role: str,
    ) -> bool:
        """Return True if IAM policy already contains a member-role binding."""
        bindings = iam_policy_dictionary.get("bindings", [])
        if not isinstance(bindings, list):
            return False

        for binding in bindings:
            if not isinstance(binding, dict):
                continue
            if binding.get("role") != iam_role:
                continue
            members = binding.get("members", [])
            if isinstance(members, list) and iam_member in members:
                return True
        return False

    def check_prerequisites(self) -> bool:
        """Verify that gcloud CLI is installed and available."""
        try:
            subprocess.run(
                [self.gcloud_executable, "--version"],
                capture_output=True,
                check=True,
            )
            self._log("✓ gcloud CLI is installed", "success")
            return True
        except (FileNotFoundError, subprocess.CalledProcessError):
            self._log("✗ gcloud CLI is not installed or missing from PATH", "error")
            self._log(
                "  Install guide: https://cloud.google.com/sdk/docs/install-gcloud-cli",
                "info",
            )
            return False

    def setup_gcloud_configuration(self) -> bool:
        """Create or activate configured gcloud configuration profile."""
        configuration_name = self.gcloud_config.get("configuration_name", "").strip()
        if not configuration_name:
            self._log(
                "⚠ No gcloud configuration_name set; using active profile",
                "warning",
            )
            return True

        self._log(
            f"\n→ Activating gcloud configuration '{configuration_name}'...",
            "info",
        )
        describe_result = self._run_command(
            [
                "gcloud",
                "config",
                "configurations",
                "describe",
                configuration_name,
            ],
            check_return_code=False,
        )

        try:
            if describe_result.returncode != 0:
                self._run_command(
                    [
                        "gcloud",
                        "config",
                        "configurations",
                        "create",
                        configuration_name,
                    ]
                )
                self._log(f"✓ Created configuration '{configuration_name}'", "success")

            self._run_command(
                [
                    "gcloud",
                    "config",
                    "configurations",
                    "activate",
                    configuration_name,
                ]
            )
            self._log(f"✓ Using configuration '{configuration_name}'", "success")
            return True
        except subprocess.CalledProcessError:
            return False

    def set_active_gcloud_account(self, account_email: str) -> bool:
        """Set active gcloud account in the current configuration profile."""
        try:
            self._run_command(["gcloud", "config", "set", "account", account_email])
            self._log(f"✓ Active account set to {account_email}", "success")
            return True
        except subprocess.CalledProcessError:
            return False

    def _collect_active_accounts(self) -> List[str]:
        """Collect active gcloud-authenticated account emails."""
        result = self._run_command(
            [
                "gcloud",
                "auth",
                "list",
                "--filter=status:ACTIVE",
                "--format=value(account)",
            ],
            check_return_code=False,
        )
        if result.returncode != 0 or not result.stdout:
            return []
        return [line.strip() for line in result.stdout.splitlines() if line.strip()]

    def ensure_authenticated_account(self) -> bool:
        """Ensure there is an active account available for gcloud operations."""
        preferred_account = self.gcloud_config.get("account", "").strip()
        active_accounts = self._collect_active_accounts()

        if preferred_account and preferred_account in active_accounts:
            self._log(f"✓ Active account available: {preferred_account}", "success")
            return self.set_active_gcloud_account(preferred_account)

        if active_accounts and not preferred_account:
            self._log(f"✓ Active account available: {active_accounts[0]}", "success")
            return True

        if not self.auth_config.get("login_if_needed", True):
            self._log("✗ No active account and login_if_needed is disabled", "error")
            return False

        self._log("\n→ Launching interactive gcloud login...", "info")
        try:
            login_command = ["gcloud", "auth", "login"]
            if preferred_account:
                login_command.append(preferred_account)
            self._run_command(login_command, capture_output=False)

            refreshed_accounts = self._collect_active_accounts()
            if not refreshed_accounts:
                self._log("✗ No active account found after login", "error")
                return False

            selected_account = preferred_account or refreshed_accounts[0]
            self._log(f"✓ Authenticated as {selected_account}", "success")
            if preferred_account:
                return self.set_active_gcloud_account(preferred_account)
            return True
        except subprocess.CalledProcessError:
            return False

    def configure_application_default_credentials(self) -> bool:
        """Ensure user ADC exists when runtime config enables ADC setup."""
        if not self.auth_config.get("create_application_default_credentials", False):
            return True

        self._log("\n→ Checking Application Default Credentials...", "info")
        token_result = self._run_command(
            ["gcloud", "auth", "application-default", "print-access-token"],
            check_return_code=False,
        )

        try:
            if token_result.returncode != 0:
                self._log("  No ADC found. Launching browser login...", "info")
                self._run_command(
                    ["gcloud", "auth", "application-default", "login"],
                    capture_output=False,
                )
                self._log("✓ Created Application Default Credentials", "success")
            else:
                self._log(
                    "✓ Application Default Credentials already available", "success"
                )

            if self.auth_config.get("set_quota_project_for_adc", True):
                self._run_command(
                    [
                        "gcloud",
                        "auth",
                        "application-default",
                        "set-quota-project",
                        self.project_id,
                    ]
                )
                self._log(f"✓ ADC quota project set to {self.project_id}", "success")
            return True
        except subprocess.CalledProcessError:
            return False

    def configure_gcloud_defaults(self) -> bool:
        """Set project and optional region/zone defaults for gcloud profile."""
        try:
            self._log(f"\n→ Setting gcloud defaults for {self.project_id}...", "info")
            self._run_command(["gcloud", "config", "set", "project", self.project_id])

            run_region = self.gcloud_config.get("run_region", "").strip()
            compute_region = self.gcloud_config.get("compute_region", "").strip()
            compute_zone = self.gcloud_config.get("compute_zone", "").strip()

            if run_region:
                self._run_command(["gcloud", "config", "set", "run/region", run_region])
            if compute_region:
                self._run_command(
                    ["gcloud", "config", "set", "compute/region", compute_region]
                )
            if compute_zone:
                self._run_command(
                    ["gcloud", "config", "set", "compute/zone", compute_zone]
                )

            self._log(f"✓ Project set to {self.project_id}", "success")
            if run_region:
                self._log(f"✓ Cloud Run region set to {run_region}", "success")
            if compute_region:
                self._log(f"✓ Compute region set to {compute_region}", "success")
            if compute_zone:
                self._log(f"✓ Compute zone set to {compute_zone}", "success")
            return True
        except subprocess.CalledProcessError:
            return False

    def _build_service_account_payload(
        self,
        action_arguments: Dict[str, Any],
    ) -> Dict[str, str]:
        """Build service account fields using defaults and action overrides."""
        default_service_account = self.defaults_config.get("service_account", {})

        service_account_name = action_arguments.get(
            "service_account_name",
            action_arguments.get("name", default_service_account.get("name", "")),
        )
        display_name = action_arguments.get(
            "display_name",
            default_service_account.get("display_name", service_account_name),
        )
        description = action_arguments.get(
            "description",
            default_service_account.get("description", ""),
        )

        service_account_email = (
            f"{service_account_name}@{self.project_id}.iam.gserviceaccount.com"
            if service_account_name
            else ""
        )

        return {
            "name": service_account_name,
            "display_name": display_name,
            "description": description,
            "email": service_account_email,
        }

    def _execute_enable_api(self, action_arguments: Dict[str, Any]) -> bool:
        """Action: enable one API service if it is not already enabled."""
        api_service_name = action_arguments.get("service", "").strip()
        if not api_service_name:
            self._log("  ✗ enable_api requires args.service", "error")
            return False

        enabled_services = set(self._collect_enabled_api_services())
        if api_service_name in enabled_services:
            self._log(f"  ✓ API already enabled: {api_service_name}", "success")
            # Diagnostic info when debugging: include enabled-services snapshot
            if self.debug_level >= 2:
                self._last_action_artifacts = {"enabled_services": list(enabled_services)}
            return True

        try:
            self._log(f"  Enabling API: {api_service_name}", "info")
            self._run_command(["gcloud", "services", "enable", api_service_name])
            self._log(f"  ✓ API enabled: {api_service_name}", "success")
            if self.debug_level >= 2:
                enabled_after = self._collect_enabled_api_services()
                self._last_action_artifacts = {"enabled_services": enabled_after}
            return True
        except subprocess.CalledProcessError:
            return False

    def _execute_ensure_service_account(
        self,
        action_arguments: Dict[str, Any],
    ) -> bool:
        """Action: create service account only if it does not already exist."""
        payload = self._build_service_account_payload(action_arguments)
        service_account_name = payload["name"]
        service_account_email = payload["email"]

        if not service_account_name:
            self._log(
                "  ✗ ensure_service_account requires service_account_name",
                "error",
            )
            return False

        self._log(f"  Ensuring service account exists: {service_account_name}", "info")
        describe_result = self._run_command(
            [
                "gcloud",
                "iam",
                "service-accounts",
                "describe",
                service_account_email,
                "--format=json",
            ],
            check_return_code=False,
        )

        if describe_result.returncode == 0:
            # try to parse JSON diagnostic output when available
            try:
                parsed = (
                    json.loads(describe_result.stdout) if describe_result.stdout else {}
                )
                self._last_action_artifacts = {"service_account": parsed}
            except Exception:
                pass
            self._log(f"  ✓ Service account exists: {service_account_name}", "success")
            return True

        try:
            create_command = [
                "gcloud",
                "iam",
                "service-accounts",
                "create",
                service_account_name,
                f"--display-name={payload['display_name']}",
            ]
            if payload["description"]:
                create_command.append(f"--description={payload['description']}")

            self._run_command(create_command)
            self._log(f"  ✓ Service account created: {service_account_name}", "success")
            # fetch and include created SA details when debugging
            if self.debug_level >= 2:
                try:
                    info_res = self._run_command(
                        [
                            "gcloud",
                            "iam",
                            "service-accounts",
                            "describe",
                            service_account_email,
                            "--format=json",
                        ],
                        check_return_code=False,
                    )
                    if info_res.returncode == 0 and info_res.stdout:
                        self._last_action_artifacts = {
                            "service_account": json.loads(info_res.stdout)
                        }
                except Exception:
                    pass
            return True
        except subprocess.CalledProcessError:
            return False

    def _build_key_file_options(
        self,
        action_arguments: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Resolve key creation options using defaults and action overrides."""
        default_credentials = self.defaults_config.get("credentials", {})

        resolved_key_directory = action_arguments.get(
            "key_path",
            default_credentials.get("key_path", "./credentials"),
        )
        resolved_key_file = action_arguments.get(
            "key_file",
            default_credentials.get("key_file", "service-account-key.json"),
        )

        return {
            "key_path": resolved_key_directory,
            "key_file": resolved_key_file,
            "overwrite_local_key": action_arguments.get(
                "overwrite_local_key",
                default_credentials.get("overwrite_local_key", False),
            ),
            "allow_new_key_creation_if_keys_exist": action_arguments.get(
                "allow_new_key_creation_if_keys_exist",
                default_credentials.get(
                    "allow_new_key_creation_if_keys_exist",
                    False,
                ),
            ),
            "delete_existing_user_managed_keys_before_create": action_arguments.get(
                "delete_existing_user_managed_keys_before_create",
                default_credentials.get(
                    "delete_existing_user_managed_keys_before_create",
                    False,
                ),
            ),
        }

    def _execute_ensure_service_account_key(
        self,
        action_arguments: Dict[str, Any],
    ) -> bool:
        """Action: create/reuse key based on safe duplicate-prevention options."""
        payload = self._build_service_account_payload(action_arguments)
        service_account_email = payload["email"]
        if not service_account_email:
            self._log(
                "  ✗ ensure_service_account_key requires service_account_name", "error"
            )
            return False

        key_options = self._build_key_file_options(action_arguments)
        key_output_path = (
            self._resolve_path(key_options["key_path"]) / key_options["key_file"]
        )
        key_output_path.parent.mkdir(parents=True, exist_ok=True)

        existing_remote_keys = self._collect_user_managed_service_account_keys(
            service_account_email,
        )

        if key_output_path.exists() and not key_options["overwrite_local_key"]:
            self._log(f"  ✓ Local key already exists: {key_output_path}", "success")
            self._log("  Skipping key creation (overwrite_local_key is false)", "info")
            return True

        if (
            existing_remote_keys
            and key_options["delete_existing_user_managed_keys_before_create"]
        ):
            self._log("  Deleting existing user-managed keys before create...", "info")
            try:
                for key_data in existing_remote_keys:
                    key_name = key_data.get("name", "")
                    if key_name:
                        self._delete_user_managed_service_account_key(
                            service_account_email,
                            key_name,
                        )
                self._log("  ✓ Deleted existing user-managed keys", "success")
                existing_remote_keys = []
            except subprocess.CalledProcessError as delete_error:
                self._log(f"  ✗ Failed deleting keys: {delete_error}", "error")
                return False

        if (
            existing_remote_keys
            and not key_options["allow_new_key_creation_if_keys_exist"]
        ):
            self._log("  ⚠ Existing user-managed keys already exist in GCP", "warning")
            self._log("  Skipping duplicate key creation", "warning")
            return True

        if key_output_path.exists() and key_options["overwrite_local_key"]:
            key_output_path.unlink()
            self._log(f"  ⚠ Removed local key file: {key_output_path}", "warning")

        try:
            self._run_command(
                [
                    "gcloud",
                    "iam",
                    "service-accounts",
                    "keys",
                    "create",
                    str(key_output_path),
                    f"--iam-account={service_account_email}",
                ]
            )
            self._log(f"  ✓ Service account key created: {key_output_path}", "success")
            # include local+remote key state in artifacts when debugging
            try:
                remote_keys = self._collect_user_managed_service_account_keys(
                    service_account_email
                )
            except Exception:
                remote_keys = []

            self._last_action_artifacts = {
                "created_files": [str(key_output_path)],
                "remote_keys": remote_keys,
            }
            return True
        except subprocess.CalledProcessError:
            return False

    def _execute_ensure_project_iam_binding(
        self,
        action_arguments: Dict[str, Any],
    ) -> bool:
        """Action: assign project IAM role only when the binding is missing."""
        role_name = action_arguments.get("role", "").strip()
        member_name = action_arguments.get("member", "").strip()

        if not member_name and action_arguments.get("service_account_name"):
            service_account_name = action_arguments["service_account_name"]
            member_name = (
                f"serviceAccount:{service_account_name}"
                f"@{self.project_id}.iam.gserviceaccount.com"
            )

        if not role_name or not member_name:
            self._log(
                "  ✗ ensure_project_iam_binding requires args.role and args.member",
                "error",
            )
            return False

        iam_policy = self._collect_project_iam_policy()
        if iam_policy and self._member_has_role_binding(
            iam_policy, member_name, role_name
        ):
            self._log(
                f"  ✓ IAM binding already exists: {member_name} -> {role_name}",
                "success",
            )
            if self.debug_level >= 2:
                self._last_action_artifacts = {"iam_policy": iam_policy}
            return True

        try:
            self._run_command(
                [
                    "gcloud",
                    "projects",
                    "add-iam-policy-binding",
                    self.project_id,
                    f"--member={member_name}",
                    f"--role={role_name}",
                    "--quiet",
                ]
            )
            # fetch updated policy for diagnostics
            try:
                iam_policy_after = self._collect_project_iam_policy()
            except Exception:
                iam_policy_after = {}

            if self.debug_level >= 2:
                self._last_action_artifacts = {"iam_policy": iam_policy_after}

            self._log(
                f"  ✓ IAM binding created: {member_name} -> {role_name}",
                "success",
            )
            return True
        except subprocess.CalledProcessError:
            return False

    def _persist_environment_variable(
        self,
        variable_name: str,
        variable_value: str,
    ) -> None:
        """Persist environment variable for future shell sessions when possible."""
        os.environ[variable_name] = variable_value
        self._log(f"  Persisting environment variable {variable_name}...", "info")

        if os.name == "nt":
            self._run_command(["setx", variable_name, variable_value])
            self._log(
                f"  ✓ Persisted {variable_name} for future Windows terminals",
                "success",
            )
            return

        self._log(
            "  ⚠ Auto persistence is only implemented for Windows.",
            "warning",
        )

    def _execute_configure_local_credentials(
        self,
        action_arguments: Dict[str, Any],
    ) -> bool:
        """Action: write env file and optional env persistence/activation."""
        payload = self._build_service_account_payload(action_arguments)
        service_account_email = payload["email"]
        if not service_account_email:
            self._log(
                "  ✗ configure_local_credentials requires service_account_name",
                "error",
            )
            return False

        default_credentials = self.defaults_config.get("credentials", {})
        key_path_value = action_arguments.get(
            "key_path",
            default_credentials.get("key_path", "./credentials"),
        )
        key_file_value = action_arguments.get(
            "key_file",
            default_credentials.get("key_file", "service-account-key.json"),
        )
        key_output_path = self._resolve_path(key_path_value) / key_file_value

        if not key_output_path.exists():
            self._log(
                "  ⚠ Local key file missing; skipping local credential configuration",
                "warning",
            )
            return True

        write_env_file = action_arguments.get(
            "write_env_file",
            default_credentials.get("write_env_file", True),
        )
        env_filename = action_arguments.get(
            "env_file",
            default_credentials.get("env_file", ".env.gcp"),
        )

        persist_google_application_credentials = action_arguments.get(
            "persist_google_application_credentials",
            default_credentials.get(
                "persist_google_application_credentials",
                False,
            ),
        )
        persist_google_cloud_project = action_arguments.get(
            "persist_google_cloud_project",
            default_credentials.get("persist_google_cloud_project", False),
        )
        activate_service_account_for_gcloud = action_arguments.get(
            "activate_service_account_for_gcloud",
            default_credentials.get("activate_service_account_for_gcloud", False),
        )

        try:
            if write_env_file:
                env_output_path = self._resolve_path(env_filename)
                env_lines = [
                    f"GOOGLE_CLOUD_PROJECT={self.project_id}",
                    f"GOOGLE_PROJECT_ID={self.project_id}",
                    f"GOOGLE_PROJECT_NUMBER={self.project_number}",
                    f"GOOGLE_APPLICATION_CREDENTIALS={key_output_path}",
                    f"GCP_SERVICE_ACCOUNT_EMAIL={service_account_email}",
                ]
                env_output_path.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
                self._log(f"  ✓ Wrote environment file: {env_output_path}", "success")
                # Record artifact(s) for structured run log
                self._last_action_artifacts = {
                    "created_files": [str(env_output_path), str(key_output_path)]
                }

            if persist_google_application_credentials:
                self._persist_environment_variable(
                    "GOOGLE_APPLICATION_CREDENTIALS",
                    str(key_output_path),
                )

            if persist_google_cloud_project:
                self._persist_environment_variable(
                    "GOOGLE_CLOUD_PROJECT",
                    self.project_id,
                )

            if activate_service_account_for_gcloud:
                self._run_command(
                    [
                        "gcloud",
                        "auth",
                        "activate-service-account",
                        service_account_email,
                        f"--key-file={key_output_path}",
                    ]
                )
                self._log("  ✓ Activated service account for gcloud", "success")

            return True
        except (OSError, subprocess.CalledProcessError) as setup_error:
            self._log(f"  ✗ Failed local credential setup: {setup_error}", "error")
            return False

    def _execute_component(
        self,
        component_item: Dict[str, Any],
    ) -> bool:
        """Execute one component item using mapped action handler."""
        # Each component is a small declarative unit of work.
        component_identifier = component_item.get("id", "unnamed-component")
        action_name = component_item.get("action", "").strip()
        is_enabled = component_item.get("enabled", True)
        raw_arguments = component_item.get("args", {})

        if not is_enabled:
            self._log(f"- Skipping disabled component: {component_identifier}", "warning")
            return True

        if not action_name:
            self._log(f"- Component '{component_identifier}' missing action", "error")
            return False

        if not isinstance(raw_arguments, dict):
            self._log(
                f"- Component '{component_identifier}' args must be an object",
                "error",
            )
            return False

        action_handler = self.action_handlers.get(action_name)
        if not action_handler:
            self._log(
                f"- Unknown action '{action_name}' in component '{component_identifier}'",
                "error",
            )
            return False

        resolved_arguments = self._resolve_argument_templates(raw_arguments)
        self._log(
            f"\n→ Executing component: {component_identifier} ({action_name})",
            "info",
        )
        # Reset last action artifacts before running
        self._last_action_artifacts = None
        try:
            result = action_handler(resolved_arguments)
            message = None
        except Exception as exc:  # catch unexpected exceptions to record them
            result = False
            message = str(exc)
            self._log(f"  ✗ Exception while executing component: {message}", "error")

        artifacts = None
        if isinstance(self._last_action_artifacts, dict):
            artifacts = self._last_action_artifacts.get("created_files")

        self._append_run_log_entry(
            component_id=component_identifier,
            action=action_name,
            args=resolved_arguments,
            result=bool(result),
            message=message,
            artifacts=artifacts,
        )

        # Clear last action artifacts for next component
        self._last_action_artifacts = None
        return result

    def execute_components(self) -> bool:
        """Execute all configured components in order from components config."""
        # Ordering is intentional: later components may depend on earlier ones.
        if not self.components:
            self._log("⚠ No components configured; nothing to execute", "warning")
            return True

        for component_item in self.components:
            if not isinstance(component_item, dict):
                self._log("✗ Component entry must be an object", "error")
                return False

            if not self._execute_component(component_item):
                return False

        return True

    def run_setup(self) -> None:
        """Run setup lifecycle: preflight, auth/defaults, component execution."""
        project_label = self.project_name or "Unnamed Project"
        self._log("=" * 60, "info")
        self._log("Google Cloud Setup Automation", "info")
        self._log("=" * 60, "info")
        self._log(f"Project: {project_label} ({self.project_id})", "info")

        if self.execution_config.get("dry_run", False):
            self._log(
                "Running in dry-run mode. No remote changes will be applied.",
                "warning",
            )

        if not self.check_prerequisites():
            sys.exit(1)

        setup_steps: List[tuple[str, Callable[[], bool]]] = [
            ("Activating gcloud configuration", self.setup_gcloud_configuration),
            ("Ensuring gcloud authentication", self.ensure_authenticated_account),
            ("Setting up ADC", self.configure_application_default_credentials),
            ("Setting gcloud defaults", self.configure_gcloud_defaults),
            ("Executing component orchestration", self.execute_components),
        ]

        failed_steps: List[str] = []
        for step_name, step_function in setup_steps:
            try:
                if not step_function():
                    failed_steps.append(step_name)
            except Exception as unexpected_error:  # noqa: BLE001
                self._log(f"✗ Error during {step_name}: {unexpected_error}", "error")
                failed_steps.append(step_name)

        # Persist run log and manifest regardless of success/failure
        try:
            self._write_run_artifacts()
        except Exception:
            # _write_run_artifacts already logs any write errors; ignore here
            pass

        self._log("\n" + "=" * 60, "info")
        if failed_steps:
            self._log("✗ Setup completed with errors:", "error")
            for failed_step_name in failed_steps:
                self._log(f"  - {failed_step_name}", "error")
            sys.exit(1)

        self._log("✓ GCP setup completed successfully", "success")
        self._log("=" * 60, "info")


def build_cli_argument_parser() -> argparse.ArgumentParser:
    """Build CLI parser for runtime config and override options."""
    parser = argparse.ArgumentParser(
        description="Automate Google Cloud setup using declarative orchestration",
    )
    parser.add_argument(
        "--config",
        default="gcp_config.yaml",
        help="Path to runtime YAML configuration file",
    )
    parser.add_argument(
        "--components-config",
        help="Override components_config.path",
    )

    parser.add_argument("--project-id", help="Override project.id")
    parser.add_argument("--project-name", help="Override project.name")
    parser.add_argument("--project-number", help="Override project.number")

    parser.add_argument(
        "--gcloud-configuration-name",
        help="Override gcloud.configuration_name",
    )
    parser.add_argument("--gcloud-account", help="Override gcloud.account")
    parser.add_argument("--run-region", help="Override gcloud.run_region")
    parser.add_argument("--compute-region", help="Override gcloud.compute_region")
    parser.add_argument("--compute-zone", help="Override gcloud.compute_zone")

    parser.add_argument(
        "--default-service-account-name",
        help="Override defaults.service_account.name",
    )
    parser.add_argument(
        "--default-key-path",
        help="Override defaults.credentials.key_path",
    )
    parser.add_argument(
        "--default-key-file",
        help="Override defaults.credentials.key_file",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print commands without applying cloud changes",
    )
    parser.add_argument(
        "--debug-level",
        type=int,
        choices=[0, 1, 2, 3],
        help="Set debug verbosity: 0=normal,1=commands,2=verbose,3=debug",
    )
    return parser


def build_cli_override_dictionary(arguments: argparse.Namespace) -> Dict[str, Any]:
    """Convert parsed CLI values to nested runtime override dictionary."""
    override_dictionary: Dict[str, Any] = {
        "project": {},
        "gcloud": {},
        "defaults": {
            "service_account": {},
            "credentials": {},
        },
        "components_config": {},
        "execution": {},
    }

    argument_mappings = [
        ("project", "id", arguments.project_id),
        ("project", "name", arguments.project_name),
        ("project", "number", arguments.project_number),
        ("gcloud", "configuration_name", arguments.gcloud_configuration_name),
        ("gcloud", "account", arguments.gcloud_account),
        ("gcloud", "run_region", arguments.run_region),
        ("gcloud", "compute_region", arguments.compute_region),
        ("gcloud", "compute_zone", arguments.compute_zone),
    ]

    # debug level mapping
    if getattr(arguments, "debug_level", None) is not None:
        override_dictionary["execution"]["debug_level"] = int(arguments.debug_level)

    for section_name, key_name, argument_value in argument_mappings:
        if argument_value:
            override_dictionary[section_name][key_name] = argument_value

    if arguments.default_service_account_name:
        override_dictionary["defaults"]["service_account"][
            "name"
        ] = arguments.default_service_account_name

    if arguments.default_key_path:
        override_dictionary["defaults"]["credentials"][
            "key_path"
        ] = arguments.default_key_path

    if arguments.default_key_file:
        override_dictionary["defaults"]["credentials"][
            "key_file"
        ] = arguments.default_key_file

    if arguments.components_config:
        override_dictionary["components_config"]["path"] = arguments.components_config

    if arguments.dry_run:
        override_dictionary["execution"]["dry_run"] = True

    return _remove_empty_nested_values(override_dictionary)


def _remove_empty_nested_values(raw_dictionary: Dict[str, Any]) -> Dict[str, Any]:
    """Remove empty nested dictionaries/lists for predictable deep-merge behavior."""
    compact_dictionary: Dict[str, Any] = {}

    for key, value in raw_dictionary.items():
        if isinstance(value, dict):
            cleaned_value = _remove_empty_nested_values(value)
            if cleaned_value:
                compact_dictionary[key] = cleaned_value
            continue

        if isinstance(value, list):
            if value:
                compact_dictionary[key] = value
            continue

        if value not in (None, ""):
            compact_dictionary[key] = value

    return compact_dictionary


def main() -> None:
    """Parse CLI arguments and execute setup automation."""
    argument_parser = build_cli_argument_parser()
    parsed_arguments = argument_parser.parse_args()

    cli_override_dictionary = build_cli_override_dictionary(parsed_arguments)
    setup_automation = GCloudSetupAutomation(
        runtime_config_path=parsed_arguments.config,
        cli_override_dictionary=cli_override_dictionary,
    )
    setup_automation.run_setup()


if __name__ == "__main__":
    main()
